apiVersion: v1
kind: Service
metadata:
  name: adshield-proxy-svc
spec:
  type: ClusterIP
  selector:
    app: adshield-proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
